import { useState, useEffect, useContext, useRef } from "react";
import style from "../styles/Game.module.css";
import Link from "next/link";
import Head from "next/head";
import {
  SquaresContext,
  ResultContext,
  HandleTileClickContext,
  IsSinglePlayerContext,
} from "./contexts/TicTacToeContext";

export default function App() {
  const [squares, setSquares] = useState(Array(9).fill(null));
  const [currentPlayer, setCurrentPlayer] = useState("X");
  const [theme, setTheme] = useState(null);
  const [isSinglePlayer, setIsSinglePlayer] = useState(true);
  const resultRef = useRef(null);

  useEffect((theme) => {
    setTheme(
      window.matchMedia("(prefers-color-scheme: dark)").matches
        ? "dark"
        : "light"
    );
    document.body.className = `${style[theme]}`;
  }, []);

  const swapPlayer = () => setCurrentPlayer(currentPlayer === "X" ? "O" : "X");

  const handleChangeTheme = () => {
    setTheme(theme === "dark" ? "light" : "dark");
  };

  const handleTileClick = (index) => {
    //return if gameOver or tile is clicked already
    if (resultRef.current || squares[index]) return;

    const newSquares = [...squares];
    newSquares[index] = currentPlayer;
    resultRef.current = getResult(newSquares); //update result

    //if game ended, rerender and quit
    if (resultRef.current) {
      setSquares(newSquares);
      return;
    }
    //game not ended. if double player, swap player and quit
    if (!isSinglePlayer) {
      setSquares(newSquares);
      swapPlayer();
      return;
    }
    //game not ended and single player.
    const nextBotMove = getBotMoveIndex(index);
    newSquares[nextBotMove] = currentPlayer === "X" ? "O" : "X";
    resultRef.current = getResult(newSquares); //update result
    setSquares(newSquares);
  };

  const getBotMoveIndex = (prevIndex) => {
    const emptyIndexes = squares
      .map((square, index) => (!square ? index : null))
      .filter((index) => index !== null && index !== prevIndex);
    if (!emptyIndexes.length) return;
    return emptyIndexes[Math.floor(Math.random() * emptyIndexes.length)];
  };

  const handleReset = () => {
    resultRef.current = null;
    setSquares(Array(9).fill(null));
    setCurrentPlayer("X");
  };

  const handlePlayerModeToggle = () => {
    setIsSinglePlayer(isSinglePlayer === true ? false : true);
    handleReset();
  };

  return (
    <>
      <Head>
        <title>Tic-Tac-Toe</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${style.main} ${style[theme]}`}>
        <MenuBar theme={theme} setTheme={handleChangeTheme} />
        <GameContextWrapper
          handleTileClick={handleTileClick}
          squares={squares}
          result={resultRef.current}
          isSinglePlayer={isSinglePlayer}
        >
          <GameContainer
            currentPlayer={currentPlayer}
            handleReset={handleReset}
            handlePlayerModeToggle={handlePlayerModeToggle}
          />
        </GameContextWrapper>
      </main>
    </>
  );
}

function MenuBar({ setTheme }) {
  return (
    <>
      <Link href="/" className={`${style.homeLink}`}>
        <u>Home</u>
      </Link>
      <button
        className={`${style.themeSelector}`}
        onClick={() => setTheme()}
      ></button>
    </>
  );
}

function GameContextWrapper(props) {
  return (
    <HandleTileClickContext.Provider value={props.handleTileClick}>
      <SquaresContext.Provider value={props.squares}>
        <ResultContext.Provider value={props.result}>
          <IsSinglePlayerContext.Provider value={props.isSinglePlayer}>
            {props.children}
          </IsSinglePlayerContext.Provider>
        </ResultContext.Provider>
      </SquaresContext.Provider>
    </HandleTileClickContext.Provider>
  );
}

function GameContainer(props) {
  return (
    <div className={style.gameContainer}>
      <Grid />
      <GameMenuBar {...props} />
    </div>
  );
}

function GameMenuBar({ handleReset, currentPlayer, handlePlayerModeToggle }) {
  const isSinglePlayer = useContext(IsSinglePlayerContext);
  const result = useContext(ResultContext);
  return (
    <div className={`${style.infoContainer}`}>
      <button className={`${style.resetButton}`} onClick={handleReset}>
        Reset
      </button>
      <button className={`${style.resetButton} ${result && style.celebrate}`}>
        {resultButtonText(result, currentPlayer)}
      </button>
      <button
        className={`${style.resetButton}`}
        onClick={handlePlayerModeToggle}
      >
        {isSinglePlayer ? "2P" : "1P"}
      </button>
    </div>
  );
}

function Grid({}) {
  return (
    <div className={style.board}>
      <Square index={0} />
      <Square index={1} />
      <Square index={2} />
      <Square index={3} />
      <Square index={4} />
      <Square index={5} />
      <Square index={6} />
      <Square index={7} />
      <Square index={8} />
    </div>
  );
}

function Square({ index }) {
  const result = useContext(ResultContext);
  const squares = useContext(SquaresContext);
  const onClick = useContext(HandleTileClickContext);

  const winningCombination = Array.isArray(result) ? [...result] : [];
  const isIconDisabled = result ? "icon-disabled" : "";
  const appearClass = squares[index] ? "appear" : "";

  return (
    <div
      className={`${style.square} ${style[indexToPositionList[index]]}`}
      onClick={() => onClick(index)}
    >
      <div
        className={`${style[appearClass]} ${style[isIconDisabled]} ${
          winningCombination.includes(index) && style.winTile
        }`}
      >
        {squares[index]}
      </div>
    </div>
  );
}

const winningCombinations = [
  [0, 1, 2],
  [3, 4, 5],
  [6, 7, 8],
  [0, 3, 6],
  [1, 4, 7],
  [2, 5, 8],
  [0, 4, 8],
  [2, 4, 6],
];

const indexToPositionList = [
  "topLeft",
  "top",
  "topRight",
  "middleLeft",
  "middle",
  "middleRight",
  "bottomLeft",
  "bottom",
  "bottomRight",
];

//decides what text to put on gameState info button
const resultButtonText = (result, currentPlayer) => {
  switch (result) {
    case "draw":
      return "It's a draw!";
    case null:
      return `${currentPlayer}, your turn now!`;
    default:
      return `${result[3]} wins!`;
  }
};

//calculates result of game; winning combination indexes or draw or null if no result
function getResult(squares) {
  for (let i = 0; i < winningCombinations.length; i++) {
    const [a, b, c] = winningCombinations[i];
    if (squares[a] && squares[a] === squares[b] && squares[a] === squares[c]) {
      return [a, b, c, squares[a]];
    }
  }
  if (squares.every((square) => square !== null)) {
    return "draw";
  }
  return null;
}
